AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Redpoint

Parameters:

  CognitoDomain:
    Type: String
    Description: A name for the Cognito Domain

  S3Bucket:
    Type: String
    Description: Parameter to specify the S3 Bucket to use for deployment

  FrontendDeployment:
    Default: remote
    Type: String
    AllowedValues:
      - local
      - remote
    ConstraintDescription: Must specify 'local' or 'remote' for FrontendDeployment.

Conditions:
  DeployCloudFront: !Equals
    - !Ref FrontendDeployment
    - remote

Globals:
  Function:
    Timeout: 20

  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'content-type,authorization'"
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn

Resources:

  #-----------------------------------------------------
  # Cognito Configuration for user management
  #-----------------------------------------------------
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      UserPoolName: !Sub ${CognitoDomain}-user-pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:8000
        - !If
          - DeployCloudFront
          - !Sub "https://${CloudfrontDistribution.DomainName}"
          - !Ref "AWS::NoValue"
      LogoutURLs:
        - http://localhost:8000
        - !If
          - DeployCloudFront
          - !Sub "https://${CloudfrontDistribution.DomainName}"
          - !Ref "AWS::NoValue"
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref UserPool


  #-----------------------------------------------------
  # CloudFront Configuration
  #-----------------------------------------------------

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Condition: DeployCloudFront
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Serverless frontend website'

  CloudfrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Condition: DeployCloudFront
    Properties:
      DistributionConfig:
        Comment: "Cloudfront distribution for serverless website"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        # List of origins that Cloudfront will connect to
        Origins:
          - Id: s3-website
            DomainName: !Sub "${S3Bucket}.s3.us-east-2.amazonaws.com"
            OriginPath: /static
            S3OriginConfig:
              # Restricting Bucket access through an origin access identity
              OriginAccessIdentity:
                Fn::Sub: 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        # To connect the CDN to the origins you need to specify behaviours
        DefaultCacheBehavior:
          # Compress resources automatically ( gzip )
          Compress: 'true'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3-website
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: DeployCloudFront
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        # Restricting access to cloudfront only.
        Statement:
          - Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"


  #-----------------------------------------------------
  # Role/Permissions/Policy Configuration
  #-----------------------------------------------------

  AccessRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'WriteToCloudWatch'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudwatch:PutMetricData
                Resource: '*'
        - PolicyName: 'AccessAreasTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/areas"

        - PolicyName: 'AccessCragsTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/crags"
        - PolicyName: 'AccessClimbsTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/climbs"
        - PolicyName: 'AccessCommentsTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/comments"
        - PolicyName: 'AccessUsersTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/users"

  #-----------------------------------------------------
  # Lambda Functions Configuration
  #-----------------------------------------------------

  GetAllAreasLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessRole.Arn
      CodeUri: RedpointLambda
      Handler: com.nashss.se.mysocialnetwork.lambda.GetAllAreasLambda::handleRequest
      Runtime: java11
      Architectures:
          - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        Redpoint:
          Type: Api
          Properties:
            Path: /areas
            Method: get

  #  GetContactLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.GetContactLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MusicPlaylistService:
  #          Type: Api
  #          Properties:
  #            Path: /contacts/{contactId}
  #            Method: get
  #
  #  GetContactsInGroupLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.GetContactsInGroupLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MusicPlaylistService:
  #          Type: Api
  #          Properties:
  #            Path: /groups/{name}/contacts
  #            Method: get
  #
  #  GetAllContactsLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.GetAllContactsLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MusicPlaylistService:
  #          Type: Api
  #          Properties:
  #            Path: /contacts
  #            Method: get
  #
  #  CreateGroupLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.CreateGroupLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MusicPlaylistService:
  #          Type: Api
  #          Properties:
  #            Path: /groups
  #            Method: post
  #
  #  CreateContactLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.CreateContactLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MusicPlaylistService:
  #          Type: Api
  #          Properties:
  #            Path: /contacts
  #            Method: post
  #
  #  GetAllGroupsLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.GetAllGroupsLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MusicPlaylistService:
  #          Type: Api
  #          Properties:
  #            Path: /groups
  #            Method: get
  #
  #  AddContactToGroupLambda:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      Role: !GetAtt AccessRole.Arn
  #      CodeUri: MySocialNetworkLambda
  #      Handler: com.nashss.se.mysocialnetwork.lambda.AddContactToGroupLambda::handleRequest
  #      Runtime: java11
  #      Architectures:
  #        - x86_64
  #      MemorySize: 512
  #      Environment:
  #        Variables:
  #          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  #      Events:
  #        MySocialNetwork:
  #          Type: Api
  #          Properties:
  #            Path: /groups/{name}/contacts
  #            Method: post

  #-----------------------------------------------------
  # DynamoDB Configuration
  #-----------------------------------------------------

  AreasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "areaId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "areaId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "areas"

  CragsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "areaId"
          AttributeType: "S"
        - AttributeName: "cragId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "areaId"
          KeyType: "HASH"
        - AttributeName: "cragId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "crags"

  ClimbsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "cragId"
          AttributeType: "S"
        - AttributeName: "climbId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cragId"
          KeyType: "HASH"
        - AttributeName: "climbId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "climbs"
      GlobalSecondaryIndexes:
        - IndexName: "ClimbId-Climb-Index"
          KeySchema:
            - AttributeName: "climbId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "users"


  CommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "time"
          AttributeType: "S"
        - AttributeName: "climbId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
        - AttributeName: "time"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "comments"
      GlobalSecondaryIndexes:
        - IndexName: "ClimbId-Comment-Index"
          KeySchema:
            - AttributeName: "climbId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

#-----------------------------------------------------
# The outputs defined below will be printed
#  to the screen after a successful deploy
#-----------------------------------------------------

Outputs:

  CognitoUserPoolId:
    Value: !Ref UserPool
    Description: "The Cognito User Pool ID (COGNITO_USER_POOL_ID)."
  CognitoUserPoolClientId:
    Value: !Ref UserPoolClient
    Description: "The Cognito User Pool Client ID (COGNITO_USER_POOL_CLIENT_ID)."
  CognitoDomain:
    Value: !Sub "${CognitoDomain}.auth.us-east-2.amazoncognito.com"
    Description: "The Cognito Domain (COGNITO_DOMAIN)."

  ApiBaseUrl:
    Description: "API Gateway endpoint base URL for Prod stage (API_BASE_URL)."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  CognitoRedirectSignin:
    Description: "The URL of the deployed front-end application (COGNITO_REDIRECT_SIGNIN)."
    Value: !Sub "https://${CloudfrontDistribution.DomainName}"
    Condition: DeployCloudFront
  CognitoRedirectSignout:
    Description: "The URL of the deployed front-end application (COGNITO_REDIRECT_SIGNOUT)."
    Value: !Sub "https://${CloudfrontDistribution.DomainName}"
    Condition: DeployCloudFront


