@startuml sequence.puml

actor "Client" as client
participant "UpdateLogbookEntryActivity" as utl
participant "LogbookEntryDao" as logbookEntryDao
database "DynamoDB" as dynamoDB

title "UpdateLogbookEntryActivity"

client -> utl : call handleRequest()
activate utl

utl -> logbookEntryDao : getLogbookEntry(entry)
activate logbookEntryDao

logbookEntryDao -> dynamoDB : lookup by logbookEntry id
activate dynamoDB

dynamoDB --> logbookEntryDao: return logbookEntry data
deactivate dynamoDB
logbookEntryDao --> utl : return LogbookEntry object

utl --> utl : update logbook entry with data from request object

utl -> logbookEntryDao : saveLogbookEntry(entry)

logbookEntryDao -> dynamoDB : save the entry
activate dynamoDB
dynamoDB -> logbookEntryDao : return the saved entry
deactivate dynamoDB
logbookEntryDao -> utl : return entry object
deactivate logbookEntryDao

utl --> client : return UpdateLogbookEntryResult built w object

@enduml
